### ISSUE TITLE
[External] Counterfactual sampling in price-tagging tutorial utils code

### ISSUE THREAD

**Issue by dangng2004** [frankaging/align-transformers#28]
Hello,

I was wondering what exactly the counterfactual sampling procedure in `lower_bound_alignment_example_sampler` does. Do the base and counterfactual labels have to be different, or can they be the same? For example, for a counterfactual label like "No", do we only want to sample base and source amounts such that the base label "Yes" is changed to "No" after intervention, or can the base label also be "No"? The code seems to suggest the latter scenario.

In that case, I put in in-line comments for what seems like a potential bug. When `base_source_regions` is [2, 3], The base left and right boundary values are (Yes, Yes), and that of the source is (Yes, No). The base label is "Yes", but after intervening on the left boundary, it is still "Yes". Any clarification is much appreciated!

<img width="368" alt="alignment_bug" src="https://github.com/frankaging/align-transformers/assets/38245908/7d409e1a-02cd-48a6-8d2e-915bee325b5c">

**Comment by frankaging** [comment]
Hey! Thanks for the inputs, and I think you are right! That row should be in the upper if block. 

If you are willing to, do you want to change that and submit PR? I will merge it as a quick fix.

On my end, I will update the tutorial results once I have more time as well as other changes needed. I will also just go back and check all my old data gen function to make sure nothing big is missing. Hopefully, this will make alignment easier to find, since it creates noise during the learning process.

Thanks again! Much appreciated!

**Comment by frankaging** [comment]
And yes, counterfactual label and base label can be the same, which is a no change (null) intervention.

**Comment by frankaging** [comment]
@dangng2004 hey, I updated the code as well as the tutorial! the evaluation results increased slightly due to this change. Thanks again for catching this!

**Comment by dangng2004** [comment]
Glad I could help!
